#pragma once

enum GameStateType
{
	EGAMESTATE_SPLASH = 0,
	EGAMESTATE_MENU = 1,
	EGAMESTATE_GAME = 2,
	EGAMESTATE_OPTIONS = 3,
	EGAMESTATE_AUDIOOPTIONS = 4,
	EGAMESTATE_GRAPHICOPTIONS = 5,
	EGAMESTATE_CONTROLOPTIONS = 6
};